import type { Metadata } from "next";

import {
  SidebarProvider,
  SidebarTrigger,
  SidebarInset,
  SidebarHeader,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import { ClerkProviderWrapper } from "@/components/providers";


export const metadata: Metadata = {
  title: "Create Clown App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        <ClerkProviderWrapper>
          <ThemeProvider 
            attribute="class" 
            defaultTheme="system" 
            enableSystem 
            disableTransitionOnChange
          >
            <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <SidebarHeader
                className={`h-14 flex flex-row items-center justify-end`}
              >
                <SidebarTrigger />
                <div className="flex items-center">
                  <ThemeToggle />
                </div>
              </SidebarHeader>
              {children}
            </SidebarInset>
            </SidebarProvider>
          </ThemeProvider>
        </ClerkProviderWrapper>
      </body>
    </html>
  );
}